### ISSUE TITLE
In README.rst, place section on prerequisites before section on Quickstart

### ISSUE THREAD

**Issue by KalmanMeth** [xlab-si/xopera-opera#118]
If a person follows the instructions in README.rst, then when running `opera deploy service.yaml` there may be an error:
```
Building wheels for collected packages: pyyaml, ansible, ansible-base
  Running setup.py bdist_wheel for pyyaml ... error
  Complete output from command /home/meth/opera/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n7ov9czm/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpgmkwja3zpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'
```
This is caused because the prerequisites (listed in the next subsection) have not been installed. 
The prerequisites should be listed in the instructions before Quickstart so the installer avoids this error.

**Comment by anzoman** [comment]
@KalmanMeth thanks for filing this issue. We will update our README and the documentation so that prerequisites for the tool will be listed before the usage.
