### ISSUE TITLE
Release 0.1.0 not working in Python 3.5

### ISSUE THREAD

**Issue by chinmaya-dehury** [xlab-si/xopera-opera#12]
As the items in a dict object in Python 3.5 are not in any ordered list, the excution workflow (in release 0.1.0) is following a random (sometime "start" -> "create" -> "configure") order. 

Good to know that xlab is now removing support for Python 3.5.
-thanks

**Comment by sstanovnik** [comment]
With Python 3.5 now having reached EOL, and 0.1.0 being a prehistoric prerelease version of `opera`, closing this.
