### ISSUE TITLE
Properties should be required by default

### ISSUE THREAD

**Issue by Legion2** [xlab-si/xopera-opera#131]
According to TOSCA YAML 1.3:
#### 3.6.10.5 Additional Requirements
> A property **SHALL** be considered <ins>required by default</ins> (i.e., as if the required keyname on the definition is set to true) unless the definition’s required keyname is explicitly set to false.

This is not enforced and also in the integration tests there are properties which have no value set even though they are required by default.

For example in the `tests/integration/misc-tosca-types/service-template.yaml` the `noimpl` node derived from `daily_test.nodes.noimpl` which defines two properties which don't specify the `required` keyname. So they SHALL be considered required. But the noimpl node does not assign values to the properties. This should be considered an error.

https://github.com/xlab-si/xopera-opera/blob/b987e566d1d42f1ed6d3b4d6b746aad5d8839632/tests/integration/misc-tosca-types/service-template.yaml#L68-L72

https://github.com/xlab-si/xopera-opera/blob/b987e566d1d42f1ed6d3b4d6b746aad5d8839632/tests/integration/misc-tosca-types/modules/node_types/noimpl/noimpl.yaml#L4-L12

**Comment by anzoman** [comment]
Thanks @Legion2! Very good find! The PR is already here: #132, so this will be fixed soon.
