### ISSUE TITLE
Enable getting current opera CLI version

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#133]
## Description
As a TOSCA compliant orchestrator, opera is constantly evolving and adding new features. This means that a lot of [develop](https://test.pypi.org/project/opera/#history) and [production](https://pypi.org/project/opera/#history) versions are getting released on [PyPI](https://pypi.org/project/opera/). Users of this tool would sometimes wanna get the current version of the opera pip package (for instance when they are debugging their templates and want to see if they have an old opera version and whether it can be updated to resolve their problems).

This already possible using the `pip show` command that displays the current version and other info for the selected the pip package, like this:
```console
(.venv) anzoman@ubuntu:~/Desktop/xopera-opera$ pip show opera
Name: opera
Version: 0.6.3.dev3
Summary: Lightweight TOSCA orchestrator
Home-page: https://github.com/xlab-si/xopera-opera
Author: XLAB d.o.o.
Author-email: pypi@xlab.si
License: UNKNOWN
Location: /home/anzoman/Desktop/xopera-opera/src
Requires: ansible, pyyaml
Required-by: 
```
However, a lot of users don't know this trick and will try to search for the version within the package itself. And I believe that it would be helpful if we establish another command switch/flag for that purposes. This would mean that `opera --version` would be a valid CLI command which would show the current version of opera package (and maybe some additional info that would be useful).

## Steps
To implement this we would need to apply the new version flag to opera's main argument parser located in `src/opera/cli.py`.

## Current behaviour
Currently it is not possible to get opera's current version from opera's CLI, but only through `pip show` command.

## Expected results
To be able to get the current Python package version of opera CLI.

**Comment by cankarm** [comment]
Thanks for putting this on the agenda @anzoman! I think that we already discussed that somewhere but the outcomes went in `/dev/null` at that point ;).

**Comment by anzoman** [comment]
The [`lastversion`](https://pypi.org/project/lastversion/) package looks promising for implementing this.

**Comment by anzoman** [comment]
Closing as `--version/-v` CLI switch was added in ff3680a590b395044407fc721149b7811655d1a8.
