### ISSUE TITLE
Add QA (quality assurance) and code testing

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#134]
## Description
Behind every successful man, there stands a .... Whatever, you name it. Here, the more important thing is that behind (almost) every successful tool, there are bunch of tests that assure its quality. The important ones are also connected to the quality of code like static code analysis, detecting code smells, code coverage, code security, vulnerabilities, code duplications, bugs and so on. In opera we are currently providing unit and integration tests (ordinary ones + nightly production tests), executing them through the CircleCI. The next important step would feature introducing code quality testing that would allow us to spot possible points of failure and would bring the users an overview of our code.

## Steps
Code Quality tests can be implemented by expanding our CI/CD configuration and by using additional tools that will perform the testing part. Here we could use some popular tools for that like [SonarQube](https://www.sonarqube.org/) or [other ones](
https://github.com/marketplace?category=code-quality) that can be integrated with GitHub and CircleCI.

## Current behaviour
Right now we don't have any real code quality testing.

## Expected results
To introduce QA tests and therefore provide better code for opera.

**Comment by cankarm** [comment]
Related, but more focused -> we would need to add the Coverage badge to show the amount of our test coverage. Should I create another issue for that? What do you think @anzoman.

**Comment by anzoman** [comment]
@cankarm thanks yeah I was also targeting this `coverage` badge and I will try to implement it soon (we can use tools like this for coverage test https://coverage.readthedocs.io/en/coverage-5.3.1/, https://circleci.com/docs/2.0/code-coverage/). We don't have to open a new issue since coverage is mentioned in the description above and I will update the status when it's done.

**Comment by anzoman** [comment]
The latest PR #165 is also connected and it will add static code analysis with sanity checks, linters, typing checks and so on.

**Comment by anzoman** [comment]
Code coverage (and also QA) will be implemented with #202. We will use [Code Climate](https://codeclimate.com/github/xlab-si/xopera-opera) for that.
