### ISSUE TITLE
wrong use of host requirement in tests

### ISSUE THREAD

**Issue by Legion2** [xlab-si/xopera-opera#145]
The node type `daily_test.nodes.noimpl` does not define a `host` requirement, because it derives from `tosca.nodes.Root` and not from `tosca.nodes.SoftwareComponent`. But in the integration test service-template.yaml a node of that node type has an assignment for the non existing requirement, which should be considered an error:

https://github.com/xlab-si/xopera-opera/blob/e5f07b51555fbd40eb10fb80d18e97817b59d1fa/tests/integration/misc_tosca_types/service-template.yaml#L73-L78

**Comment by anzoman** [comment]
@Legion2 many thanks for spotting this! I will take a look and try to resolve it.
