### ISSUE TITLE
Requirement Assignments must have matching Requirement definitions

### ISSUE THREAD

**Issue by Legion2** [xlab-si/xopera-opera#182]
Requirement can only be assigned in a node template if they have been defined in the node type. But in `tests/integration/misc_tosca_types/service-template.yaml` the `test` node template assigns the `host` requirement which is not defined by its type:
https://github.com/xlab-si/xopera-opera/blob/bd1cd5cee95de212b141394123722f9deb6b4126/tests/integration/misc_tosca_types/service-template.yaml#L96-L99

The node type `daily_test.nodes.test` only defines the requirements `host1` and `host2`:
https://github.com/xlab-si/xopera-opera/blob/bd1cd5cee95de212b141394123722f9deb6b4126/tests/integration/misc_tosca_types/modules/node_types/test/test.yaml#L42-L48

The error was introduced in https://github.com/xlab-si/xopera-opera/commit/b85cc4f5e547c098efeb20add035716baab248f5#diff-06330f6fa8504094c2f63f7d0ae4feea739be1e279c88f4581a00c3f115a101cR95-R97

**Comment by anzoman** [comment]
@Legion2 thanks for finding and opening this! We have to fix the current behaviour.

**Comment by anzoman** [comment]
Found out that this same issue was actually spotted some time ago in #63.
