### ISSUE TITLE
Limit max number of NodeExtecutor's worker threads

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#183]
## Description
The orchestrator offers parallelization of workers for `opera deploy` and `opera undeploy` CLI commands. With `-w/--workers` CLI option the users specifies the maximum number of concurrent deployment threads (a positive number, default is 1). Apart from having the lower limit for workers we might also want to have an upper limit to prevent any uncertain deployment scenarios.

## Steps
Set the upper limit for `-w/--workers` for deploy and undeploy CLI commands (using range).

## Current behaviour
The maximum number of workers is not limited.

## Expected results
To limit the max number of concurrent workers (e.g. to 64)

**Comment by anzoman** [comment]
@cankarm, @sstanovnik, @dradx what limit do you propose? Will the maximum of 64 workers be enough?

**Comment by cankarm** [comment]
@anzoman This is probably maximum, I would say that even 32 or 16 are quite suitable limits. Maybe in HPC if they need to install something more complex, like whole MPI environments they might require 64 or more? @dradX it there any HPC use case with extra-large concurrency requirements?

**Comment by alexmaslenn** [comment]
@anzoman number of workers `-w/--workers` is exactly the upper limit. Lower limit is determined by template topology.

**Comment by dradX** [comment]
@anzoman @cankarm Maybe we should first discuss why do we need to set up a max number at all? Given that we are not crunching numbers here and we usually do remote deployment steps through Ansible?

**Comment by anzoman** [comment]
@alexmaslenn here we were targetting one additional limit for the maximum number of workers within the CLI/Node executor that is not determined by user but is pre-defined.

@dradX I agree, we should discuss this. Although the user can set the desired number of workers, the upper limit is still based on the number of independent nodes in the TOSCA service template and therefore we might not need an additional upper limit. But still if the user's system cannot run more than some number of threads this could lead to some unexpected results or errors. 

@cankarm what do you think?

**Comment by anzoman** [comment]
After all I think that there's no need to change the pre-defined max number of threads because this could limit the users too much and we can leave the maximum value undefined for now. Another thing is that `ThreadPoolExecutor` that we use for launching concurrent tasks already calculates the max number of workers based on the OS:

> Python’s ThreadPoolExecutor uses a pool of threads to execute asynchronous tasks. Also a subclass of Executor, it uses a defined number of maximum worker threads (at least five by default, according to the formula min(32, os.cpu_count() + 4)) and reuses idle threads before starting new ones, making it pretty efficient. (https://www.freecodecamp.org/news/multithreaded-python/)

I'm closing this issue and we can reopen anytime if we'll ever have to.
