### ISSUE TITLE
xOpera does not detect missing requirements

### ISSUE THREAD

**Issue by mikidep** [xlab-si/xopera-opera#211]
## Steps to replicate
 - Install `opera` and download this repository;
 - Edit the file `examples/nginx_openstack/service.yaml` removing the `requirements` section in node `site`;
 - Run `opera validate examples/nginx_openstack/service.yaml`.

## Expected behaviour
xOpera should complain about the missing requirement.

## Current behaviour
xOpera validates the template without errors.

## Possible cause of the issue
In file `src/opera/template/node.py`, in method `resolve_requirements`, only requirements that appear in the node template are checked; requirements specified in the node type that do not appear in the node template are not. In fact, it seems that node type information in general is not carried over to the parsed topology, but only the type name is.

**Comment by anzoman** [comment]
Hi, many thanks for bringing this up, we'll try to resolve this issues as soon as possible.

**Comment by anzoman** [comment]
This has been fixed in cf52b433b612002ac56da96033c0c41dfb2a8ad3 and considering the example above `opera` would now output `Missing requirements: host`.
