### ISSUE TITLE
Fix invalid keys error for TOSCA properties

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#229]
## Description
In the latest weeks we've been updating our xOpera examples. This was needed due to some remaining [TOSCA v1.3](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html) inconsistencies and it looks like that some of these issues also uncovered some bugs in our xOpera TOSCA [parser](https://github.com/xlab-si/xopera-opera/tree/master/src/opera/parser). 

The affect of our changes is visible in the [xopera-examples](https://github.com/xlab-si/xopera-examples) repository, where our CI validation is currently [failing](https://github.com/xlab-si/xopera-examples/runs/4205236506?check_suite_focus=true). The validation fails with `lib/types.yaml:34:13: [PropertyDefinition] Invalid keys: value` error, which is probably because we don't support the extended syntax for TOSCA properties.

## Steps
Fix errors in the TOSCA [parser](https://github.com/xlab-si/xopera-opera/tree/master/src/opera/parser).

## Current behaviour
xOpera is unable to parse and deploy the updated examples.

## Expected results
To fix the bugs in the parser and be able to deploy the latest TOSCA examples.

### Note
The issue described here was also discussed in https://github.com/xlab-si/xopera-opera/discussions/228.

**Comment by philippemerle** [comment]
The xOpera TOSCA parser was fixed by https://github.com/xlab-si/xopera-opera/commit/701838255c660700679d73112ba1392d08fcd6f8.
Certaintly the CI installs and uses the current xOpera pip module which does not contain this fix.
Deploying a new version of xOpera on pip should resolve the issue.

**Comment by anzoman** [comment]
Hi, @philippemerle yes it's true and I've totally forgotten that you fixed this.

So, until we release a new [production](https://pypi.org/project/opera/#history) version, the users can use a [development](https://test.pypi.org/project/opera/#history) version from TestPyPI. 

This can be achieved by running:

```console
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ opera==0.6.8.dev8
```

Therefore this issue can be closed.
