### ISSUE TITLE
Normative networking types missing in src/opera/stdlib/v_1_3.yaml

### ISSUE THREAD

**Issue by philippemerle** [xlab-si/xopera-opera#230]
Following normative TOSCA networking types are not defined in src/opera/stdlib/v_1_3.yaml:

* tosca.capabilities.network.Linkable
* tosca.nodes.network.Network
* tosca.nodes.network.Port
* tosca.relationships.network.LinksTo
* tosca.relationships.network.BindsTo

My next PR will add them.

**Comment by anzoman** [comment]
Thanks for spotting this @philippemerle!
