### ISSUE TITLE
Provide additional info in OperationError

### ISSUE THREAD

**Issue by alexmaslenn** [xlab-si/xopera-opera#233]
In case of node operation failed `OperationalError` is raised. Currently this exception contains no meaningful info, but it would be convenient to have:
1. Name of the node failed
2. Name of the interface failed
3. Name of the operation failed

This would significantly help to present the users of xOpera as SaaS a nice description of the problem that occurred.  

Additionally it would be great to extract some meaningful info from Ansible output like the name of the failed task, its message and stderr.

**Comment by anzoman** [comment]
Thanks @alexmaslenn, this could be a great enhancement.
