### ISSUE TITLE
Cannot use an unset value: public_address

### ISSUE THREAD

**Issue by abitrolly** [xlab-si/xopera-opera#245]
`opera` fails if `service.yaml` for Compute doesn't specify `public_address` as **attribute**.

```
Cannot use an unset value: public_address
```

I expected to set only properties, but such property is invalid. I am setting the Ansible host and port from playbook, so it counter intuitive that `opera` fails to read this attribute even if it is unused. In fact, I would expect it to set it automatically from Ansible host if nothing else is supplied.

**Comment by anzoman** [comment]
Hi, @abitrolly can you post here your full TOSCA CSARs - i.e., all TOSCA templates and Ansible playbooks you're using to deploy?

**Comment by abitrolly** [comment]
It is a contract work, so I can not share it yet.

**Comment by anzoman** [comment]
@abitrolly aha okay can you than recreate this beaviour with some other TOSCA template and Ansible playbook?

**Comment by abitrolly** [comment]
No. It turned to be a lot of hacks on top of each other. Something finally worked, but I don't have the motivation to redo the thing from scratch. The experiment is simple - try to use `tosca.nodes.Compute` in either types definition or in instance, but I am drained. I could probably try to run copyrighted examples, but again no motivation. If you can't repeat this, might be some mistake on my side.
