### ISSUE TITLE
Some files linked to the main TOSCA yaml are not accessible to the orchestrator. 

### ISSUE THREAD

**Issue by cankarm** [xlab-si/xopera-opera#25]
In the case of the CSAR-tree, the orchestrator ignores the referenced file defined in the main TOSCA yaml and returns a

`[Path] Path <path to the file> does not exist.`

type of error. The referenced file is in the same folder then the main file.

**Comment by tadeboro** [comment]
Fixes for this are included in the latest stable version on [pypi](https://pypi.org/project/opera/) (0.5.5 at the moment).
