### ISSUE TITLE
Support for compressed CSARs

### ISSUE THREAD

**Issue by cankarm** [xlab-si/xopera-opera#27]
Current release supports CSARs, but not the compressed version of CSAR.

**Comment by anzoman** [comment]
This issue was addressed in #55. Now opera supports deploying/undeploying service templates and also the compressed CSAR files. This was achieved by implementing `opera init` command and the deployment can be done as follows:

```console
# initialize the CSAR (from the prepared compressed CSAR file) 
# also provide inputs
opera init --inputs inputs.yaml

# deploy the initialized CSAR
opera deploy

# uddeploy the deployed CSAR
opera deploy
```

So I guess that this is it - we can close the issue!
