### ISSUE TITLE
Improve validation for symlinks

### ISSUE THREAD

**Issue by matejart** [xlab-si/xopera-opera#38]
When `opera` runs in the production mode or in pretty much any setting where user-controlled input gets accepted, content validation should reject any symlinks within the CSAR. Currently, this is implemented [here](https://github.com/xlab-si/xopera-opera/commit/1d9b6750f4dd871cacffdf9fd36fa63f4c187331#r39246909).

However, I was able to use a symlink in my environment between the `base_path` and the actually imported file, and the validation failed to notice that. So we should strengthen this.

At the same time, I would like to continue using this approach in my development setting, so I am willing to supply an `--unsafe-dont-use-in-production-allow-symlinks` kind of switch.

**Comment by anzoman** [comment]
@sstanovnik can you verify that the simlinks now fully work within a TOSCA CSAR?

**Comment by cankarm** [comment]
Closing, as there was not report, that simlinks would not work.
