### ISSUE TITLE
Use case: Develop and test a service template

### ISSUE THREAD

**Issue by matejart** [xlab-si/xopera-opera#40]
Use case: Develop and test a service template
=============================================

## Description

This use case addresses the need of developers of service templates to be able
to test their work as it progresses with a reasonable ease.

## Prerequisites

* `opera` is installed in the actor's working environment.

## Steps

* Developer creates a new project and authors a service template:

      $ mkdir -p ~/project/demo-055 && cd ~/project/demo-055
      $ $EDITOR inputs.yaml service.yaml

* Developer initializes the deployment environment for the service in the
  editable mode:

      $ opera init --editable .

* Developer runs the deploy of the service:

      $ opera deploy --inputs inputs.yaml --template service.yaml

* Developer then runs an undeploy:

      $ opera undeploy

* Developer makes changes to `service.yaml`.
* Developer runs the deploy of the updated service:

      $ opera deploy --inputs inputs.yaml --template service.yaml

## Expected results

* The service gets deployed according to the latest update of the service template.

## Comment

* The developer may skip the step where she invokes `undeploy`, but the results may be unexpected in this case.

**Comment by cankarm** [comment]
Do you expect that before undeploy user can run:
- validate (check if TOSCA file is still in a good shape)
- diff (check the differences between deployments - create a tree for both blueprints and show the diff).

**Comment by matejart** [comment]
No, `undeploy` uses the same (i.e., a copy of) the service template used in the latest preceeding `deploy`, so there is no expectation of change.

**Comment by cankarm** [comment]
Sorry, I put that out wrong -  I mean before **deploy**, e.g. before you want to force the updated version, the user has a possibility to use a command that makes a diff and visually (e.g. in text) points out the differences.

**Comment by matejart** [comment]
That sounds like a new use case. In my use case described here, I present the case where you run `undeploy` before doing the next `deploy`. You could skip the `undeploy` part, but the outcome may not be what you expect.

**Comment by anzoman** [comment]
This issue has been inactive for almost a year now and TOSCA service templates and CSAR can now be deployed easiiy with opera. We can reopen this issue if we need in the future.
