### ISSUE TITLE
Use case: Develop and test a TOSCA library

### ISSUE THREAD

**Issue by matejart** [xlab-si/xopera-opera#41]
## Description

This use case addresses the need of a developer of a [TOSCA library](https://github.com/xlab-si/xopera-opera/issues/41#issuecomment-630784044) to modify and test the library definitions and implementation with a relative convenience.

## Prerequisites

* The TOSCA library project initiated in, for example, `~/libraries/example`.
* A project, e.g., `~/projects/test-example` containing a service template to use the library.
* `opera` is installed in the actor's working environment.

## Steps

* Developer makes a symbolic link in the service template project to the TOSCA library project:

      $ cd ~/projects/test-example
      $ mkdir -p library
      $ ln -s ~/libraries/example library/example

* Developer initializes the deployment environment for the service in the editable mode and in the symlink-unsafe mode:

      $ opera init --allow-symlinks --editable .
      WARNING: You have enabled the use of symbolic links in the service template
      definition, which could lead to security issues. Please proceed responsibly!

* Developer runs the deploy of the service:

      $ opera deploy --inputs inputs.yaml --template service.yaml --allow-symlinks
      WARNING: You have enabled the use of symbolic links in the service template
      definition, which could lead to security issues. Please proceed responsibly!

## Expected results

* The service gets deployed according to the latest changes of the service template.
* The service gets deployed also using the latest changes of the imported TOSCA library.

**Comment by anzoman** [comment]
I see that his issue raises a lot of new possibilities and also questions. But could you explain what exactly is this TOSCA library and what it's capable of doing? From my perspective I see it as a special kind of storage for service templates that can be connected to xOpera. And also - would this library be a part of opera itself or just an adjacent repository that will need to be used for these kind of deployments you posted here?

**Comment by matejart** [comment]
@anzoman thank you for good questions.

I would define a TOSCA library as a redistributable and reusable collection of TOSCA definitions and corresponding interface operation implementations. It can provide a TOSCA profile for a specific domain. It is a fully distinct entity from opera. It can be included in an arbitrary service template and is usable in service deployment.

So the library would sit on a designated place on your hard drive. When packaging the CSAR, it gets incorporated into the CSAR.

**Comment by anzoman** [comment]
@matejart thanks for the explanation and for making things much more clear to me. Also it's nice to see you opened the PR connected to this enhancement which will allow us to discuss things there even further and to jump into details.

**Comment by anzoman** [comment]
This issue has been inactive for almost a year now and we have also developed a separated [Template library](https://template-library-radon.xlab.si/) component that  serves as a place for storing TOSCA templates and CSARs. So, therefore I'm closing this issue and we can reopen it in the future if we need.
