### ISSUE TITLE
Transfer opera documentation to this repository

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#47]
## Description
This use case addresses the possibility to relocate xOpera's documentation. Currently the documentation for opera orchestrator is available here: https://xlab-si.github.io/xopera-docs/ and originates from this repository: https://github.com/xlab-si/xopera-docs. The documentation was initially created to present opera orchestration tool as a micosite for Horizon 2020 RADON project and for the fast creation it was put in a separate repository but there's no doubt that through time the documentation will be extended and will explain opera's components in detail. Therefore I think that we should keep things considering opera together and so that opera's docs could also be a part of this repository. 

## Prerequisites

- Read the Docs account (optional)

## Steps

1. I suggest that we first create `docs` folder here at the root of opera's repository. This directory would contain all the documentation files (.rst files) and other assets that would be displayed in our docs.

2. The next step would feature creating a new PR that would move the current documentation files here. For the documentation rendering we can use Sphinx tool and prepare a Makefile that builds the HTML documentation files which can be actually hosted somewhere. And as we are already here for the hosting we can use GitHub Pages.

3. So after the documentation source files are fully prepared we can create a special branch called `gh-pages`, build the docs and push them on this branch (here we shouldn't forget the `.nojekyll file` in order to prevent GitHub Pages from needlessly running Jekyll themes.). 

4. And eventually under the repository settings we can mark to build the xOpera's GitHub Pages site from `gh-pages` branch. 

## Expected results
To have the documentation source files in this repository (in `docs` folder) and the documentation available on: https://xlab-si.github.io/xopera-opera/.

## Note
There is also another way of doing all that which is to create an account at https://readthedocs.org/, upload the documentation there and connect this to GitHub but this is suitable only if we want to use Read the Docs style for our documentation.

**Comment by sstanovnik** [comment]
Resolved by #60.
