### ISSUE TITLE
Provided example lacking instructions

### ISSUE THREAD

**Issue by MysteriousWolf** [xlab-si/xopera-opera#5]
Provided instructions are not sufficient for a successful launch of the provided example.
OpenStack provides 2 different options for .rc file downloads. Provided documentation doesn't state whether you need a v2.0 or v3 one.
Also, before launching the provided example you have to generate an ssh key pair in OpenStack and add it to the id_rsa file in the ssh folder.

**Comment by gberginc** [comment]
Can you propose the update of the documentation in a PR based on your findings?

**Comment by matejart** [comment]
Thank you for this report.
The documentation is currently written with someone who has been using Ansible and possibly OpenStack, so it lacks any warnings or prerequisites that would introduce someone new. So perhaps a note that one should be able to connect to the OpenStack using the regular ssh up front would help? Then there can be a troubleshooting section with cases that you have encountered. Picking which version of .rc file depends on the environment, but the newer one might work more likely. There might be an openstack cli command to verify that first. If the ssh connection doesn't work, the user might need to check if their ssh key lets them in a manually spun up VM.

**Comment by anzoman** [comment]
Update: we will try to add more info about this in the updated documentation about opera which will be available on GitHub pages.

**Comment by anzoman** [comment]
The example is now explained a little bit better in our [docs](https://xlab-si.github.io/xopera-docs/) and in our [xopera-examples ](https://github.com/xlab-si/xopera-examples) repository. So I'm closing this one and we can reopen if we'll need to do some additional explanations to the docs.
