### ISSUE TITLE
Parallelization of declarative workflow execution

### ISSUE THREAD

**Issue by alexmaslenn** [xlab-si/xopera-opera#51]
## Description
In order to improve deployment performance, it would be useful to parallelize deployment execution. In the situation when direct acyclic graph (DAG) representing the node dependencies can be drawn as a tree with two separate branches xOpera should run node deployment concurrently.
## Prerequisites
- `opera` installed
- `service.yaml` TOSCA Service Template containing node templates that could be deployed concurrently (e.g. 2 independent tosca.nodes.Compute with hosted tosca.nodes.SoftwareComponent).
## Steps
- User runs deploy `opera deploy service.yaml`
## Current behavior
- Ansible scripts for node deployment are executed sequentially.
## Expected behavior
- Ansible scripts for node deployment are executed simultaneously.

**Comment by matejart** [comment]
Thank you for this ticket, @alexmaslenn . The implementation will be greatly useful for working with deployments.
Just a question: do you foresee a command-line switch for setting the number of workers, or for choosing to run the workflow fully sequentially?
Also, the same extension should apply for `undeploy`.

**Comment by alexmaslenn** [comment]
@matejart was thinking to make the number of workers an environment variable, the same way it is done for default Ansible user. But probably your approach is more flexible and explicit. Thanks. 

Same logic applies for undeploy for sure.

**Comment by alexmaslenn** [comment]
@matejart @anzoman I have a question regarding parallel execution output. In sequential deployment an output would look like this:
```
Deploying my-workstation_0
Deploying hello-1_0
  Executing create on hello-1_0
  Executing start on hello-1_0
Deploying hello-2_0
  Executing create on hello-2_0
  Executing start on hello-2_0
Deploying hello-3_0
  Executing create on hello-3_0
  Executing start on hello-3_0
Deploying hello-4_0
  Executing create on hello-4_0
  Executing start on hello-4_0
```
while in parallel it is obviously more messy
```
Deploying my-workstation_0
Deploying hello-2_0
Deploying hello-3_0
  Executing create on hello-2_0
  Executing create on hello-3_0
Deploying hello-4_0
  Executing create on hello-4_0
Deploying hello-1_0
  Executing create on hello-1_0
  Executing start on hello-4_0
  Executing start on hello-1_0
  Executing start on hello-2_0
  Executing start on hello-3_0
```
Would this output be ok or we should put effort to maintain same output order as for sequesntial deployment (e.g. collecting all prints for separate node deployment and returning them at the end of operation)?

**Comment by matejart** [comment]
@alexmaslenn thank you for bringing this up. I'd be perfectly happy with the output that is prefixed by some sort of a worker identifier, e.g.:

```
[Worker-001] Deploying my-workstation_0
[Worker-001] Deploying hello-2_0
[Worker-002] Deploying hello-3_0
[Worker-001]   Executing create on hello-2_0
[Worker-002]   Executing create on hello-3_0
[Worker-003] Deploying hello-4_0
[Worker-003]   Executing create on hello-4_0
[Worker-004] Deploying hello-1_0
[Worker-004]   Executing create on hello-1_0
[Worker-003]   Executing start on hello-4_0
[Worker-004]   Executing start on hello-1_0
[Worker-001]   Executing start on hello-2_0
[Worker-002]   Executing start on hello-3_0
```

Putting them in order later might be too much work for too little value.

**Comment by dradX** [comment]
@alexmaslenn is this done or we need to add something to close this issue?

**Comment by dradX** [comment]
This issue was closed by this PR [Implement concurrent deploy/undeploy execution #65](https://github.com/xlab-si/xopera-opera/pull/65).
