### ISSUE TITLE
Possible parsing confilct spotted in TOSCA group type members

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#53]
## Description
The section 3.7.11 of the [TOSCA YAML profile v1.3](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#_Toc26969477) talks about TOSCA Group Type. Amongst its attributes and properties there is also a keyname called `members` which is referred to as:

> an optional list of one or more names of Node Types that  are valid (allowed) as members of the Group Type. 

Below that there is a simple example explaining the usage and the syntax for the Group Types. But what is strange is that there seems to be another definition of the `members` keyname which is to be:

> the optional list of TOSCA types (e.g.,., Node, Capability or even other Group Types) that are valid member types for being added to (i.e., members of) the Group Type.

So from that one may conclude that members of the group are not just node types but also all the other TOSCA types. So what would be the right way to treat those members?

![TOSCA Group Type](https://user-images.githubusercontent.com/41727816/83734116-dcc85d80-a64e-11ea-9175-75d7ac12ee98.png)

## Current behaviour
As of now xOpera allows to create group types and reference them in `groups` section of the service template. But is it currently possible just to add node types to this group but not also references to other types because if you try to than opera fails with `Invalid reference` error. This is because our parser sees group members only as nodes (`members=List(Reference("node_types"))`). So here if members can contain other TOSCA types we would probably need to modify the parser and create some kind of an `xor` class operation for all possible target references.

## Expected results
To be able to add other TOSCA types (apart from node types) to a group type.

**Comment by matejart** [comment]
This language survives in the 2.0, which suggests that nobody else either encountered it or took exception to it.

So unless we have real need (i.e.: solid use cases) for extending the meaning of the Group Type members, I'd keep the current implementation.

**Comment by anzoman** [comment]
Ok, I just came across this when trying to implement policy type targets that as well allow to hold group types or node types so I discovered group type members and saw that something isn't right. I see that in [TOSCA YAML 2.0](https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd01/TOSCA-v2.0-csd01.html) the description is the same.

For now we don't have any requests to extend the Group Type members with other types apart nodes. So I think that we can skip this for now.

And I think that you accidentally marked the wrong man in the comment above ;)

**Comment by matejart** [comment]
> And I think that you accidentally marked the wrong man in the comment above ;)
Embarrassing 😲 I apologise! 😑

I still hold it's a good find and a good thing to keep a note on.

**Comment by anzoman** [comment]
No problem :smile: , so we can keep that issue open in case that this will be brought up again in the future.

**Comment by anzoman** [comment]
It seems that we were right when allowing just node types, the draft of [TOSCA `2.0` ](https://docs.oasis-open.org/tosca/TOSCA/v2.0/TOSCA-v2.0.html) has been updated and now it states that only nodes are allowed as valid members for the group type. 

![image](https://user-images.githubusercontent.com/41727816/118106412-e0776f00-b3dd-11eb-9c2e-193f3bebf0ad.png)

I think we can close that now.
