### ISSUE TITLE
Migrate CI/CD from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by anzoman** [xlab-si/xopera-opera#66]
## Description
Currently xOpera uses CircleCI for Continuous Integration and Continuous Deployment. The free plan we are using includes 2500 free credits per week (on Linux machines 10 credits per minute are used), running 1 job at a time and building on Linux and Windows executors. CircleCI has proved to be a reliable CI/CD solution but now the contribution on xOpera GitHub repository is growing and free plan limits might bring some drawbacks as the problem with lack of credits may arise and we won't be able to use CI/CD jobs then. Therefore I propose to make a substitution in CI/CD provider and use GitHub Actions to invoke our CI/CD jobs. GH Actions seem to have no limits for public repositories and to be more friendly for open-source solutions (like opera):

> Actions are completely free for every open-source repository and include 2000 free build minutes per month for all your private repositories which is comparable with most CI/CD free plans.

## Steps
In order to use GitHub Action instead of CIrcleCI we would need to rewrite our CI/CD configuration and create some CI/CD workflows. The good sigh is that the syntax of both CI/CD providers is not so  different and both are using YAML.

## Current behaviour
As of now xOpera uses CircleCI to trigger CI/CD pipelines

## Expected results
To replace CircleCI with GitHub Actions and thereby use them for testing, building and releasing xOpera.

## Note
@tadeboro also expressed the possibility of migration to GH Actions way before me and I'm just putting his suggestion to this issue in order for us to be able to decide if this migration is the right thing to do.

**Comment by tadeboro** [comment]
I just noticed this on our CircleCI dashboard:

![image](https://user-images.githubusercontent.com/70951/85027486-47fb4f00-b17a-11ea-9f45-88b424d614c5.png)

Is our CI stuff still running or did CircleCI cut us off?

And yes, if we hit the plan limits, there is no other option besides migrating somewhere else.

**Comment by tadeboro** [comment]
I did a quick search (again) about CircleCI and opens source stuff and it looks like open source repositories have a higher limit: 400,000 credits per month per organization. And I am pretty sure we will not hit that anytime soon. So maybe this migration can wait a bit longer ;)

**Comment by anzoman** [comment]
Yes I've been surprised too when I saw that minus. But wow, 400,000 credits seems to be enough for us. And yes I agree that we can wait and do this migration someday in the future if we will really need it for some other beneficial reason.

**Comment by anzoman** [comment]
Migration was done in #252.
