### ISSUE TITLE
Add SODALITE project reference in readme Ackowledgments section

### ISSUE THREAD

**Issue by dradX** [xlab-si/xopera-opera#69]
### Description 
SODALITE project provides issues, comments and feature implementation to xOpera development.

### Current state
Currently there is the RADON project reference in the Acknowledgement section of the readme.rst file.

### Expected state
A reference to SODALITE (project no. 825480) is added to Acknowledgements section.

**Comment by matejart** [comment]
Thank you, @dradX , I agree that this makes sense. Will you or someone in your group go ahead and make a PR to address this?
