### ISSUE TITLE
Consider using the Puccini TOSCA compiler

### ISSUE THREAD

**Issue by tliron** [xlab-si/xopera-opera#9]
Currently xOpera implements its own embedded TOSCA parser written in Python. This is a difficult task, considering the evolving complexity of the language. I've worked on a previous attempt in Python, [AriaTosca](https://github.com/apache/incubator-ariatosca) (an Apache Software Foundation incubator project), and am now working on the [Puccini TOSCA compiler](https://github.com/tliron/puccini), which is written in Go but is a simple, stateless executable that can be straightforwardly called from Python. Puccini aims to provide comprehensive TOSCA ingestion that can be integrated into orchestrators.

I'd like to humbly suggest that xOpera can instead make use of the Puccini instead of building its own parser. I would of course be thrilled if we could work together to improve Puccini to make it work well for xOpera!

**Comment by matejart** [comment]
Thank you for your offer! I appreciate it, and at least from the standpoint of fighting the not-invented-here paradigm, it makes sense. However, we have considered both AriaTosca before and Puccini TOSCA, but after internal discussion decided to nevertheless spin up our own compiler. We are confident in our ability to build and maintain a compiler in Python that is also well suited for our purpose in the orchestrator. We are not as well-versed in Go, which we feel would be a hinderance in being a valuable contributor to Puccini.

That said, we are open for suggestions and comments.

**Comment by tliron** [comment]
Thank you for considering! For what it;s worth, moving from Python to Go feels quite natural after a time. They occupy similar spaces in the devops world and indeed many projects have done the shift. I probably don't have time to look closely at your parser as well as Puccini, but am happy to help out with specific questions if you hit them and want to know how they were handled here. Hopefully vice versa is OK. It's generally good that there are many implementations of the spec.
