### ISSUE TITLE
`create.yml` does not exist when running `opera outputs`

### ISSUE THREAD

**Issue by duelle** [xlab-si/xopera-opera#99]
This issue seems to behave similar to #81 just for the `outputs` command.

`/tmp % opera outputs

.opera/csars/csar/_definitions/radonnodesdocker__DockerEngine.tosca:35:24: [Path] Path /tmp/nodetypes/radon.nodes.docker/DockerEngine/files/create/create.yml does not exist.`

The file not found exists in `/tmp/.opera/csars/csar/nodetypes/radon.nodes.docker/DockerEngine/files/create/create.yml` though.

**Comment by duelle** [comment]
Might be related to #96

**Comment by anzoman** [comment]
Thanks @duelle for bringing this up. I believe that the PR #96 that you mentioned will fix this also.

**Comment by anzoman** [comment]
@duelle we added some bugfixes within #96 and think that this might be fixed now. You can give it a try with testing opera pacakge on Test PyPI : https://test.pypi.org/project/opera/0.6.2.dev4/.

**Comment by anzoman** [comment]
Closing this as it was fixed with #96.
